### ISSUE TITLE
Unreadable/blocked-out product labels?

### ISSUE THREAD

**Issue by markjam33** [jturner65/StraffordSOMVis#7]
When I turn on "Show Products" in the UI, the products light up as yellow markers on the map. However, to the right of each marker is what I assume should be the label, but this is showing as four white blocks instead of text. Could this be a font problem? See attached screenshot, noting the product markers.
<img width="1480" alt="Screen Shot 2019-05-09 at 2 17 20 PM" src="https://user-images.githubusercontent.com/2717316/57476882-8d560900-7265-11e9-82bb-5e33b9599642.png">

**Comment by jturner65** [comment]
This might be because multiple products are being displayed on top of each other.
